// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package queries

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const batchUpsertTargetStatus = `-- name: BatchUpsertTargetStatus :batchexec
INSERT INTO file_backup_target_status ("externalID", target, state, "storedBytes", "verifiedAt")
VALUES ($1, $2, $3, $4, CASE WHEN $3 = 'stored' THEN now() ELSE NULL END)
ON CONFLICT ("externalID", target)
DO UPDATE SET
  -- never downgrade a durable 'stored' row to 'failed'
  state = CASE WHEN file_backup_target_status.state = 'stored' AND EXCLUDED.state <> 'stored'
               THEN file_backup_target_status.state ELSE EXCLUDED.state END,
  -- storedBytes / verifiedAt only advance on a fresh successful store
  "storedBytes" = CASE WHEN EXCLUDED.state = 'stored' THEN EXCLUDED."storedBytes"
                       ELSE file_backup_target_status."storedBytes" END,
  "verifiedAt" = CASE WHEN EXCLUDED.state = 'stored' THEN now()
                      ELSE file_backup_target_status."verifiedAt" END
`

type BatchUpsertTargetStatusBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BatchUpsertTargetStatusParams struct {
	ExternalID  string      `json:"externalID"`
	Target      string      `json:"target"`
	State       string      `json:"state"`
	StoredBytes pgtype.Int8 `json:"storedBytes"`
}

func (q *Queries) BatchUpsertTargetStatus(ctx context.Context, arg []BatchUpsertTargetStatusParams) *BatchUpsertTargetStatusBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ExternalID,
			a.Target,
			a.State,
			a.StoredBytes,
		}
		batch.Queue(batchUpsertTargetStatus, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BatchUpsertTargetStatusBatchResults{br, len(arg), false}
}

func (b *BatchUpsertTargetStatusBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BatchUpsertTargetStatusBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
