// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const coverageGaps = `-- name: CoverageGaps :one
SELECT (
  (SELECT count(*) FROM file_backup_object)
  - (SELECT count(*) FROM (
      SELECT "externalID" FROM file_backup_target_status
      WHERE state = 'stored' AND target = ANY($1::text[])
      GROUP BY "externalID" HAVING count(*) >= $2::int
    ) fully))::bigint AS gaps
`

type CoverageGapsParams struct {
	Targets     []string `json:"targets"`
	TargetCount int32    `json:"target_count"`
}

// Objects NOT stored on every configured target = total objects MINUS fully-replicated
// objects. The total is an EXACT count (a coverage backstop must not under-report), bounded
// by the coarse sample cadence.
// ::bigint on the result so sqlc emits int64 (count(*) is bigint); a bare subtraction was
// inferred as int32, which would ERROR the scan past 2^31 objects rather than return the count.
func (q *Queries) CoverageGaps(ctx context.Context, arg CoverageGapsParams) (int64, error) {
	row := q.db.QueryRow(ctx, coverageGaps, arg.Targets, arg.TargetCount)
	var gaps int64
	err := row.Scan(&gaps)
	return gaps, err
}

const lastVerifiedAge = `-- name: LastVerifiedAge :one
SELECT
  count(*) FILTER (WHERE mv IS NULL) AS never_verified,
  COALESCE(EXTRACT(EPOCH FROM max(now() - mv)), 0)::float8 AS stalest_age_sec
FROM (
  SELECT (SELECT max("verifiedAt") FROM file_backup_target_status
          WHERE target = t AND state = 'stored') AS mv
  FROM unnest($1::text[]) AS t
) per_target
`

type LastVerifiedAgeRow struct {
	NeverVerified int64   `json:"never_verified"`
	StalestAgeSec float64 `json:"stalest_age_sec"`
}

// The RPO signal over the CONFIGURED targets: never_verified = count of targets that have
// verified NOTHING, stalest_age_sec = age of the stalest target that HAS verified. Probing
// each target via unnest counts a from-inception-empty target as never-verified rather than
// dropping it from a GROUP BY. COALESCE(...,0) keeps the column NON-NULL (0 at bootstrap when
// nothing has verified anywhere) so it scans into float64; the caller derives "nothing yet"
// from never_verified == number of targets, not from a nullable age.
func (q *Queries) LastVerifiedAge(ctx context.Context, targets []string) (LastVerifiedAgeRow, error) {
	row := q.db.QueryRow(ctx, lastVerifiedAge, targets)
	var i LastVerifiedAgeRow
	err := row.Scan(&i.NeverVerified, &i.StalestAgeSec)
	return i, err
}

const listStoredTargets = `-- name: ListStoredTargets :many
SELECT target FROM file_backup_target_status
WHERE "externalID" = $1 AND state = 'stored'
`

// The set of targets already in state='stored' for an object — the dedup source of truth.
func (q *Queries) ListStoredTargets(ctx context.Context, externalID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStoredTargets, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var target string
		if err := rows.Scan(&target); err != nil {
			return nil, err
		}
		items = append(items, target)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const probe = `-- name: Probe :one
SELECT EXISTS(SELECT 1 FROM file_backup_object) AS obj,
       EXISTS(SELECT 1 FROM file_backup_target_status) AS status
`

type ProbeRow struct {
	Obj    bool `json:"obj"`
	Status bool `json:"status"`
}

// Both ledger tables exist + are readable via the pool's role: a skipped migration makes
// the query ERROR (relation does not exist); an EMPTY table is success. EXISTS returns a
// NON-NULL boolean (false on empty) so the row scans cleanly — a bare (SELECT 1 ... LIMIT 1)
// would yield NULL on an empty table and fail a non-null scan.
func (q *Queries) Probe(ctx context.Context) (ProbeRow, error) {
	row := q.db.QueryRow(ctx, probe)
	var i ProbeRow
	err := row.Scan(&i.Obj, &i.Status)
	return i, err
}

const recordBackup = `-- name: RecordBackup :exec

WITH obj AS (
  INSERT INTO file_backup_object ("externalID", size, "createdBy", "sourceCreatedDate")
  VALUES ($1, $3, $4, $5)
  ON CONFLICT ("externalID") DO UPDATE
    SET size = CASE WHEN $6::bool THEN EXCLUDED.size ELSE file_backup_object.size END
)
INSERT INTO file_backup_target_status ("externalID", target, state, "storedBytes", "verifiedAt")
SELECT $1, t.target, t.state, t.bytes, CASE WHEN t.state = 'stored' THEN now() ELSE NULL END
FROM jsonb_to_recordset($2::jsonb) AS t(target text, state text, bytes bigint)
ON CONFLICT ("externalID", target) DO UPDATE SET
  state = CASE WHEN file_backup_target_status.state = 'stored' AND EXCLUDED.state <> 'stored'
               THEN file_backup_target_status.state ELSE EXCLUDED.state END,
  "storedBytes" = CASE WHEN EXCLUDED.state = 'stored' THEN EXCLUDED."storedBytes"
                       ELSE file_backup_target_status."storedBytes" END,
  "verifiedAt" = CASE WHEN EXCLUDED.state = 'stored' THEN now()
                      ELSE file_backup_target_status."verifiedAt" END
`

type RecordBackupParams struct {
	ExternalID        string             `json:"external_id"`
	Statuses          []byte             `json:"statuses"`
	Size              int64              `json:"size"`
	CreatedBy         uuid.NullUUID      `json:"created_by"`
	SourceCreatedDate pgtype.Timestamptz `json:"source_created_date"`
	SizeVerified      bool               `json:"size_verified"`
}

// The ledger tables are THIS service's own (db/migrations). Per constitution §IV all their
// SQL is defined here and compiled by sqlc — the hand-written pgx exceptions were removed.
// Every 'stored' literal below MUST equal domain.StateStored; it is a stable ledger-schema
// value that changes only via a coordinated migration (grep 'stored' here finds each site).
// The object row (FK parent) + every per-target status in ONE atomic data-modifying CTE:
// the object is inserted first so the FK check on the status rows sees it (same statement).
// The statuses arrive as a single jsonb array decoded via jsonb_to_recordset — a multi-arg
// unnest(text[],text[],bigint[]) is what sqlc's analyzer can't type, so the whole statement
// (and one-RTT atomicity) can now be compiled by sqlc instead of hand-written pgx. size is
// corrected to a later VERIFIED value but never downgraded to unverified outbox hearsay; a
// stored status stamps verifiedAt=now() and never regresses stored->failed.
func (q *Queries) RecordBackup(ctx context.Context, arg RecordBackupParams) error {
	_, err := q.db.Exec(ctx, recordBackup,
		arg.ExternalID,
		arg.Statuses,
		arg.Size,
		arg.CreatedBy,
		arg.SourceCreatedDate,
		arg.SizeVerified,
	)
	return err
}

const storedCountByTarget = `-- name: StoredCountByTarget :many
SELECT target, count(*)::bigint AS n
FROM file_backup_target_status
WHERE state = 'stored' AND target = ANY($1::text[])
GROUP BY target
`

type StoredCountByTargetRow struct {
	Target string `json:"target"`
	N      int64  `json:"n"`
}

// Count of objects currently stored per configured target — the restore-all completeness snapshot,
// so an operator sees per-target disparity before trusting a single-source restore. Index-only on
// (target, state). A target with no rows is simply absent from the result (the caller fills 0).
func (q *Queries) StoredCountByTarget(ctx context.Context, targets []string) ([]StoredCountByTargetRow, error) {
	rows, err := q.db.Query(ctx, storedCountByTarget, targets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredCountByTargetRow{}
	for rows.Next() {
		var i StoredCountByTargetRow
		if err := rows.Scan(&i.Target, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storedExternalIDsPage = `-- name: StoredExternalIDsPage :many
SELECT "externalID" FROM file_backup_target_status
WHERE target = $1 AND state = 'stored' AND "externalID" > $2 COLLATE "C"
ORDER BY "externalID" COLLATE "C" LIMIT $3
`

type StoredExternalIDsPageParams struct {
	Target    string `json:"target"`
	After     string `json:"after"`
	PageLimit int32  `json:"page_limit"`
}

// Just the externalIDs stored ON one target, keyset-paged by externalID — what the audit
// sweep needs (it re-probes the sink and consumes ONLY the id). Unlike StoredObjectsPage this
// does NOT join file_backup_object, so it is a covering INDEX-ONLY scan on
// (target, state, "externalID") with no per-row heap fetch for size/createdBy the audit
// discards. COLLATE "C" pins byte order (see StoredObjectsPage) so the ledger stream and the
// manifest agree on ordering in the inventory diff.
func (q *Queries) StoredExternalIDsPage(ctx context.Context, arg StoredExternalIDsPageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, storedExternalIDsPage, arg.Target, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var externalID string
		if err := rows.Scan(&externalID); err != nil {
			return nil, err
		}
		items = append(items, externalID)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storedObjectsPage = `-- name: StoredObjectsPage :many
SELECT o."externalID", o.size, o."createdBy", o."sourceCreatedDate"
FROM file_backup_object o
JOIN file_backup_target_status ts ON ts."externalID" = o."externalID"
WHERE ts.target = $1 AND ts.state = 'stored' AND o."externalID" > $2 COLLATE "C"
ORDER BY o."externalID" COLLATE "C" LIMIT $3
`

type StoredObjectsPageParams struct {
	Target    string `json:"target"`
	After     string `json:"after"`
	PageLimit int32  `json:"page_limit"`
}

type StoredObjectsPageRow struct {
	ExternalID        string             `json:"externalID"`
	Size              int64              `json:"size"`
	CreatedBy         uuid.NullUUID      `json:"createdBy"`
	SourceCreatedDate pgtype.Timestamptz `json:"sourceCreatedDate"`
}

// Objects stored ON one target (manifest/audit), keyset-paged by externalID; the
// (target, state, "externalID") index makes the WHERE+ORDER an index-ordered range scan. The
// explicit COLLATE "C" pins BYTE order (matching the column collation + the byte-order `<` the
// audit inventory diff and manifestIterator's monotonicity check assume) so it can't drift on a
// locale-collated database. This is DELIBERATELY redundant with the column's COLLATE "C" (migration
// 000002) — keep BOTH: the query-level COLLATE guarantees byte-ordered RESULTS even on a ledger where
// 000002 has not run (an older v0.0.1/v0.0.2 DB), so mergeInventory never miscounts; the column-level
// COLLATE makes the covering index serve this order without a sort. Dropping either is a bug (wrong
// merge order, or a silent per-page seq-scan+sort on a large corpus).
func (q *Queries) StoredObjectsPage(ctx context.Context, arg StoredObjectsPageParams) ([]StoredObjectsPageRow, error) {
	rows, err := q.db.Query(ctx, storedObjectsPage, arg.Target, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StoredObjectsPageRow{}
	for rows.Next() {
		var i StoredObjectsPageRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.Size,
			&i.CreatedBy,
			&i.SourceCreatedDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const targetGapsPage = `-- name: TargetGapsPage :many
SELECT o."externalID",
  COALESCE(array_agg(ts.target) FILTER (WHERE ts.state = 'stored' AND ts.target = ANY($1::text[])), '{}')::text[] AS stored
FROM file_backup_object o
LEFT JOIN file_backup_target_status ts ON ts."externalID" = o."externalID"
WHERE o."externalID" > $2
GROUP BY o."externalID"
HAVING count(*) FILTER (WHERE ts.state = 'stored' AND ts.target = ANY($1::text[])) < $3::int
ORDER BY o."externalID" LIMIT $4
`

type TargetGapsPageParams struct {
	Targets     []string `json:"targets"`
	After       string   `json:"after"`
	TargetCount int32    `json:"target_count"`
	PageLimit   int32    `json:"page_limit"`
}

type TargetGapsPageRow struct {
	ExternalID string   `json:"externalID"`
	Stored     []string `json:"stored"`
}

// One keyset page (externalID order) of under-replicated objects with the CURRENT targets
// that DO hold each. An object stored on all target_count targets is excluded (HAVING);
// stale statuses for removed targets are filtered out (target = ANY(targets)).
func (q *Queries) TargetGapsPage(ctx context.Context, arg TargetGapsPageParams) ([]TargetGapsPageRow, error) {
	rows, err := q.db.Query(ctx, targetGapsPage,
		arg.Targets,
		arg.After,
		arg.TargetCount,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TargetGapsPageRow{}
	for rows.Next() {
		var i TargetGapsPageRow
		if err := rows.Scan(&i.ExternalID, &i.Stored); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
