// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getObject = `-- name: GetObject :one
SELECT "externalID", size, "firstSeenAt", "createdBy", "sourceCreatedDate", "mimeType" FROM file_backup_object WHERE "externalID" = $1
`

func (q *Queries) GetObject(ctx context.Context, externalid string) (FileBackupObject, error) {
	row := q.db.QueryRow(ctx, getObject, externalid)
	var i FileBackupObject
	err := row.Scan(
		&i.ExternalID,
		&i.Size,
		&i.FirstSeenAt,
		&i.CreatedBy,
		&i.SourceCreatedDate,
		&i.MimeType,
	)
	return i, err
}

const getTargetStatus = `-- name: GetTargetStatus :one
SELECT state, "storedBytes" FROM file_backup_target_status
WHERE "externalID" = $1 AND target = $2
`

type GetTargetStatusParams struct {
	ExternalID string `json:"externalID"`
	Target     string `json:"target"`
}

type GetTargetStatusRow struct {
	State       string      `json:"state"`
	StoredBytes pgtype.Int8 `json:"storedBytes"`
}

func (q *Queries) GetTargetStatus(ctx context.Context, arg GetTargetStatusParams) (GetTargetStatusRow, error) {
	row := q.db.QueryRow(ctx, getTargetStatus, arg.ExternalID, arg.Target)
	var i GetTargetStatusRow
	err := row.Scan(&i.State, &i.StoredBytes)
	return i, err
}

const upsertObject = `-- name: UpsertObject :exec
INSERT INTO file_backup_object ("externalID", size, "createdBy", "sourceCreatedDate", "mimeType")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("externalID") DO NOTHING
`

type UpsertObjectParams struct {
	ExternalID        string             `json:"externalID"`
	Size              int64              `json:"size"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	SourceCreatedDate pgtype.Timestamptz `json:"sourceCreatedDate"`
	MimeType          pgtype.Text        `json:"mimeType"`
}

func (q *Queries) UpsertObject(ctx context.Context, arg UpsertObjectParams) error {
	_, err := q.db.Exec(ctx, upsertObject,
		arg.ExternalID,
		arg.Size,
		arg.CreatedBy,
		arg.SourceCreatedDate,
		arg.MimeType,
	)
	return err
}

const upsertTargetStatus = `-- name: UpsertTargetStatus :exec
INSERT INTO file_backup_target_status ("externalID", target, state, "storedBytes", "verifiedAt")
VALUES ($1, $2, $3, $4, now())
ON CONFLICT ("externalID", target)
DO UPDATE SET state = EXCLUDED.state, "storedBytes" = EXCLUDED."storedBytes", "verifiedAt" = now()
`

type UpsertTargetStatusParams struct {
	ExternalID  string      `json:"externalID"`
	Target      string      `json:"target"`
	State       string      `json:"state"`
	StoredBytes pgtype.Int8 `json:"storedBytes"`
}

func (q *Queries) UpsertTargetStatus(ctx context.Context, arg UpsertTargetStatusParams) error {
	_, err := q.db.Exec(ctx, upsertTargetStatus,
		arg.ExternalID,
		arg.Target,
		arg.State,
		arg.StoredBytes,
	)
	return err
}
