// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FileBackupObject struct {
	ExternalID        string             `json:"externalID"`
	Size              int64              `json:"size"`
	FirstSeenAt       pgtype.Timestamptz `json:"firstSeenAt"`
	CreatedBy         pgtype.UUID        `json:"createdBy"`
	SourceCreatedDate pgtype.Timestamptz `json:"sourceCreatedDate"`
	MimeType          pgtype.Text        `json:"mimeType"`
}

type FileBackupTargetStatus struct {
	ExternalID  string             `json:"externalID"`
	Target      string             `json:"target"`
	State       string             `json:"state"`
	StoredBytes pgtype.Int8        `json:"storedBytes"`
	VerifiedAt  pgtype.Timestamptz `json:"verifiedAt"`
}
