// Package db holds the domain-facing outbox and ledger ports. The low-level,
// type-safe query layer is generated by sqlc into ./queries (T005/T006/T013).
package db

import (
	"context"
	"errors"
)

// ErrNotImplemented marks scaffold stubs pending the pgx/sqlc implementation.
var ErrNotImplemented = errors.New("db: not implemented (TODO T005/T006/T013)")

// OutboxEntry is a claimed outbox row (alkemio DB).
type OutboxEntry struct {
	ID         int64
	FileID     string
	ExternalID string
	Priority   int16
}

// Outbox is the read/claim side of the outbox in the Alkemio DB (scoped role):
// LISTEN wakeups + FOR UPDATE SKIP LOCKED claim + mark-done.
type Outbox interface {
	// Claim atomically claims up to n pending rows (priority DESC, createdDate).
	Claim(ctx context.Context, n int) ([]OutboxEntry, error)
	// MarkDone marks an entry done once all required targets confirm.
	MarkDone(ctx context.Context, id int64) error
}

// Ledger is the backup metadata store in this service's own DB.
type Ledger interface {
	// UpsertObject records an object (idempotent).
	UpsertObject(ctx context.Context, externalID string, size int64) error
	// UpsertTargetStatus records per-(object,target) completion.
	UpsertTargetStatus(ctx context.Context, externalID, target, state string) error
}
